export interface Plant {
  id: number;
  name: string;
  scientificName: string;
  fileName: string;
  family: string;
  genus: string;
  notes: string;
  relatedId: number[];
  reading: string;
  link: string;
}

export const plants: Plant[] = [
  {
    id: 0,
    name: "",
    scientificName: "",
    fileName: "",
    family: "",
    genus: "",
    notes: "",
    relatedId: [],
    reading: "",
    link: ""
  },
  {
    id: 1,
    name: "朧月",
    scientificName: "Graptopetalum paraguayense",
    fileName: "graptopetalum-paraguayense",
    family: "ベンケイソウ科",
    genus: "グラプトペタルム属",
    notes: "",
    relatedId: [32, 33, 34],
    reading: "オボロヅキ",
    link: ""
  },
  {
    id: 2,
    name: "初恋",
    scientificName: "Douglas Huth",
    fileName: "douglas-huth",
    family: "ベンケイソウ科",
    genus: "グラプトベリア属",
    notes: "",
    relatedId: [],
    reading: "ハツコイ",
    link: ""
  },
  {
    id: 3,
    name: "万象 白虎",
    scientificName: "Byakko",
    fileName: "byakko",
    family: "キジカクシ科ツルボラン亜科",
    genus: "ハオルチア属",
    notes: "",
    relatedId: [],
    reading: "バンショウ ビャッコ",
    link: ""
  },
  {
    id: 4,
    name: "薄氷",
    scientificName: "Graptoveria 'Caerulescens'",
    fileName: "graptoveria-caerulescens",
    family: "ベンケイソウ科",
    genus: "グラプトベリア属",
    notes: "",
    relatedId: [202, 203],
    reading: "ハクヒョウ",
    link: "/echeveria-battle-whitepeony-vs-lightice/"
  },
  {
    id: 5,
    name: "斑入り丸葉万年草",
    scientificName: "Variegata",
    fileName: "variegata",
    family: "ベンケイソウ科",
    genus: "マンネングサ属",
    notes: "",
    relatedId: [],
    reading: "フイリマルバマンネングサ",
    link: ""
  },
  {
    id: 6,
    name: "青リンゴ",
    scientificName: "Blue Apple",
    fileName: "",
    family: "ベンケイソウ科",
    genus: "セデベリア属",
    notes: "",
    relatedId: [7],
    reading: "アオリンゴ",
    link: ""
  },
  {
    id: 7,
    name: "ブルーエルフ",
    scientificName: "Blue Elf",
    fileName: "",
    family: "ベンケイソウ科",
    genus: "セデベリア属",
    notes: "",
    relatedId: [6],
    reading: "ブルーエルフ",
    link: ""
  },
  {
    id: 8,
    name: "火祭り",
    scientificName: "Crassula capitella 'Camp Fire'",
    fileName: "crassula-capitella-camp-fire",
    family: "ベンケイソウ科",
    genus: "クラッスラ属",
    notes: "",
    relatedId: [255],
    reading: "ヒマツリ",
    link: ""
  },
  {
    id: 9,
    name: "ブラウンローズ",
    scientificName: "Echeveria 'Brown Rose'",
    fileName: "echeveria-brown-rose",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [],
    reading: "ブラウンローズ",
    link: ""
  },
  {
    id: 10,
    name: "ホワイトストーンクロプ",
    scientificName: "Whitestonecrop",
    fileName: "whitestonecrop",
    family: "ベンケイソウ科",
    genus: "セデベリア属",
    notes: "",
    relatedId: [],
    reading: "ホワイトストーンクロプ",
    link: ""
  },
  {
    id: 11,
    name: "ビクターケーン",
    scientificName: "Victor Kane",
    fileName: "victor-kane",
    family: "ベンケイソウ科",
    genus: "グラプトペタルム属",
    notes: "",
    relatedId: [],
    reading: "ビクターケーン",
    link: ""
  },
  {
    id: 12,
    name: "ピンクルルビー",
    scientificName: "Graptoveria 'Pinkle Ruby'",
    fileName: "graptoveria-pinkle-ruby",
    family: "ベンケイソウ科",
    genus: "グラプトベリア属",
    notes: "",
    relatedId: [13, 200, 201],
    reading: "ピンクルルビー",
    link: ""
  },
  {
    id: 13,
    name: "ピンクルビー",
    scientificName: "Graptoveria 'Pinkle Ruby'",
    fileName: "graptoveria-pinkle-ruby",
    family: "ベンケイソウ科",
    genus: "グラプトベリア属",
    notes: "",
    relatedId: [12, 200, 201],
    reading: "ピンクルビー",
    link: ""
  },
  {
    id: 14,
    name: "フェイスライクジェイド",
    scientificName: "Face like jade",
    fileName: "face-like-jade",
    family: "",
    genus: "",
    notes: "",
    relatedId: [],
    reading: "フェイスライクジェイド",
    link: ""
  },
  {
    id: 15,
    name: "ピンクベリー",
    scientificName: "Canny Hinny",
    fileName: "pink-berry",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [16],
    reading: "ピンクベリー",
    link: ""
  },
  {
    id: 16,
    name: "ピンクベリー",
    scientificName: "Pink Berry",
    fileName: "pink-berry",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [15],
    reading: "ピンクベリー",
    link: ""
  },
  {
    id: 17,
    name: "姫秋麗",
    scientificName: "Graptopetalum mendozae",
    fileName: "graptopetalum-mendozae",
    family: "ベンケイソウ科",
    genus: "グラプトペタルム属",
    notes: "",
    relatedId: [],
    reading: "ヒメシュウレイ",
    link: ""
  },
  {
    id: 18,
    name: "ピーチプリティ",
    scientificName: "Peach Pretty",
    fileName: "peach-pretty",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [],
    reading: "ピーチプリティ",
    link: ""
  },
  {
    id: 19,
    name: "パープルディライト",
    scientificName: "Purple Delight",
    fileName: "purple-delight",
    family: "ベンケイソウ科",
    genus: "グラプトペタルム属",
    notes: "",
    relatedId: [],
    reading: "パープルディライト",
    link: ""
  },
  {
    id: 20,
    name: "ヘラクレス",
    scientificName: "Heracles",
    fileName: "heracles",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [],
    reading: "ヘラクレス",
    link: ""
  },
  {
    id: 21,
    name: "プロリフィカ",
    scientificName: "Echeveria prolifica",
    fileName: "echeveria-prolifica",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [231],
    reading: "プロリフィカ",
    link: ""
  },
  {
    id: 22,
    name: "ブルーライト",
    scientificName: "Blue Light",
    fileName: "blue-light",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [],
    reading: "ブルーライト",
    link: ""
  },
  {
    id: 23,
    name: "ハウォルヤ",
    scientificName: "Hawolya",
    fileName: "hawolya",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [],
    reading: "ハウォルヤ",
    link: ""
  },
  {
    id: 24,
    name: "フロリディティ",
    scientificName: "Floridity",
    fileName: "floridity",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [],
    reading: "フロリディティ",
    link: ""
  },
  {
    id: 25,
    name: "ラウリンゼ",
    scientificName: "Laulindsa",
    fileName: "laulindsa",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [],
    reading: "ラウリンゼ",
    link: "/laurinza-revelation-2/"
  },
  {
    id: 26,
    name: "セイバー",
    scientificName: "",
    fileName: "saber",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [],
    reading: "セイバー",
    link: "/edum-sabre-charm-care-guide/"
  },
  {
    id: 27,
    name: "花うらら",
    scientificName: "Pulidonis",
    fileName: "pulidonis",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [],
    reading: "ハナウララ",
    link: ""
  },
  {
    id: 28,
    name: "パープルヘイズ",
    scientificName: "Purple Haze",
    fileName: "purple-haze",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [],
    reading: "パープルヘイズ",
    link: ""
  },
  {
    id: 29,
    name: "ペンタンドルム",
    scientificName: "Pentandrum",
    fileName: "pentandrum",
    family: "ベンケイソウ科",
    genus: "グラプトペタルム属",
    notes: "",
    relatedId: [],
    reading: "ペンタンドルム",
    link: ""
  },
  {
    id: 30,
    name: "ブラッククイーン",
    scientificName: "Echeveria 'Black Queen'",
    fileName: "echeveria-black-queen",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [],
    reading: "ブラッククイーン",
    link: "/blackqueen-beauty-care/"
  },
  {
    id: 31,
    name: "ハンベルティー",
    scientificName: "humbertii",
    fileName: "humbertii",
    family: "ベンケイソウ科",
    genus: "クラッスラ属",
    notes: "",
    relatedId: [],
    reading: "ハンベルティー",
    link: ""
  },
  {
    id: 32,
    name: "おぼろ月",
    scientificName: "Graptopetalum paraguayense",
    fileName: "graptopetalum-paraguayense",
    family: "ベンケイソウ科",
    genus: "グラプトペタルム属",
    notes: "",
    relatedId: [1, 33, 34],
    reading: "オボロヅキ",
    link: ""
  },
  {
    id: 33,
    name: "石蓮花",
    scientificName: "Graptopetalum paraguayense",
    fileName: "graptopetalum-paraguayense",
    family: "ベンケイソウ科",
    genus: "グラプトペタルム属",
    notes: "",
    relatedId: [1, 32, 34],
    reading: "セキレンカ",
    link: ""
  },
  {
    id: 34,
    name: "パラグアイエンセ",
    scientificName: "Graptopetalum paraguayense",
    fileName: "graptopetalum-paraguayense",
    family: "ベンケイソウ科",
    genus: "グラプトペタルム属",
    notes: "",
    relatedId: [1, 32, 33],
    reading: "パラグアイエンセ",
    link: ""
  },
  {
    id: 35,
    name: "インディカ",
    scientificName: "Indica",
    fileName: "indica",
    family: "ベンケイソウ科",
    genus: "シノクラッスラ属",
    notes: "",
    relatedId: [],
    reading: "インディカ",
    link: ""
  },
  {
    id: 36,
    name: "ゴーラム",
    scientificName: "Gollum",
    fileName: "gollum",
    family: "ベンケイソウ科",
    genus: "クラッスラ属",
    notes: "",
    relatedId: [37, 38, 39],
    reading: "ゴーラム",
    link: ""
  },
  {
    id: 37,
    name: "宇宙の木",
    scientificName: "Gollum",
    fileName: "gollum",
    family: "ベンケイソウ科",
    genus: "クラッスラ属",
    notes: "",
    relatedId: [36, 38, 39],
    reading: "ウチュウノキ",
    link: ""
  },
  {
    id: 38,
    name: "ゴラム",
    scientificName: "Gollum",
    fileName: "gollum",
    family: "ベンケイソウ科",
    genus: "クラッスラ属",
    notes: "",
    relatedId: [36, 37, 39],
    reading: "ゴラム",
    link: ""
  },
  {
    id: 39,
    name: "オバータ・ゴーラム",
    scientificName: "Gollum",
    fileName: "gollum",
    family: "ベンケイソウ科",
    genus: "クラッスラ属",
    notes: "",
    relatedId: [36, 37, 38],
    reading: "オバータ・ゴーラム",
    link: ""
  },
  {
    id: 40,
    name: "エメラルドリップル",
    scientificName: "Emerald Ripple",
    fileName: "emerald-ripple",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "セトーサ E. setosa と乙女 E. amoena との交配種。E. 'Ron Evans' と同種。",
    relatedId: [],
    reading: "エメラルドリップル",
    link: ""
  },
  {
    id: 41,
    name: "霜の朝",
    scientificName: "Powder Puff",
    fileName: "powder-puff",
    family: "ベンケイソウ科",
    genus: "パキベリア属",
    notes: "",
    relatedId: [42, 43],
    reading: "シモノアシタ",
    link: ""
  },
  {
    id: 42,
    name: " パウダーパフ",
    scientificName: "Powder Puff",
    fileName: "powder-puff",
    family: "ベンケイソウ科",
    genus: "パキベリア属",
    notes: "",
    relatedId: [41, 43],
    reading: "パウダーパフ",
    link: ""
  },
  {
    id: 43,
    name: "エキゾチカ",
    scientificName: "Powder Puff",
    fileName: "powder-puff",
    family: "ベンケイソウ科",
    genus: "パキベリア属",
    notes: "",
    relatedId: [41, 42],
    reading: "エキゾチカ",
    link: ""
  },
  {
    id: 44,
    name: "愛染錦",
    scientificName: "domesticum f.variegata",
    fileName: "domesticum-f-variegata",
    family: "ベンケイソウ科",
    genus: "アエオニウム属",
    notes: "",
    relatedId: [],
    reading: "アイゾメニシキ",
    link: ""
  },
  {
    id: 45,
    name: "乙女心",
    scientificName: "Pachyphyllum",
    fileName: "pachyphyllum",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [46, 47, 48],
    reading: "オトメゴコロ",
    link: "/love-and-romance-in-the-world-of-succulents/"
  },
  {
    id: 46,
    name: "アツバベンケイ",
    scientificName: "Pachyphyllum",
    fileName: "pachyphyllum",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [45, 47, 48],
    reading: "アツバベンケイ",
    link: "/love-and-romance-in-the-world-of-succulents/"
  },
  {
    id: 47,
    name: "パキフィラム",
    scientificName: "Pachyphyllum",
    fileName: "pachyphyllum",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [45, 46, 48],
    reading: "パキフィラム",
    link: "/love-and-romance-in-the-world-of-succulents/"
  },
  {
    id: 48,
    name: "厚葉弁慶",
    scientificName: "Pachyphyllum",
    fileName: "pachyphyllum",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [45, 46, 47],
    reading: "アツバベンケイ",
    link: "/love-and-romance-in-the-world-of-succulents/"
  },
  {
    id: 49,
    name: "黄麗",
    scientificName: "Golden Glow",
    fileName: "golden-glow",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [50, 51, 52],
    reading: "オウレイ",
    link: ""
  },
  {
    id: 50,
    name: "月の王子",
    scientificName: "Golden Glow",
    fileName: "golden-glow",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [49, 51, 52],
    reading: "ツキノオウジ",
    link: ""
  },
  {
    id: 51,
    name: "オウレイ ",
    scientificName: "Golden Glow",
    fileName: "golden-glow",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [49, 50, 52],
    reading: "オウレイ",
    link: ""
  },
  {
    id: 52,
    name: "ゴールデングロー",
    scientificName: "Golden Glow",
    fileName: "golden-glow",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [49, 50, 51],
    reading: "ゴールデングロー",
    link: ""
  },
  {
    id: 53,
    name: "花月",
    scientificName: "Ovata",
    fileName: "ovata",
    family: "ベンケイソウ科",
    genus: "クラッスラ属",
    notes: "",
    relatedId: [54, 55, 56, 57, 58, 59],
    reading: "カゲツ",
    link: ""
  },
  {
    id: 54,
    name: "カネノナルキ",
    scientificName: "Ovata",
    fileName: "ovata",
    family: "ベンケイソウ科",
    genus: "クラッスラ属",
    notes: "",
    relatedId: [53, 55, 56, 57, 58, 59],
    reading: "カネノナルキ",
    link: ""
  },
  {
    id: 55,
    name: "金のなる木",
    scientificName: "Ovata",
    fileName: "ovata",
    family: "ベンケイソウ科",
    genus: "クラッスラ属",
    notes: "",
    relatedId: [53, 54, 56, 57, 58, 59],
    reading: "カネノナルキ",
    link: ""
  },
  {
    id: 56,
    name: "成金草",
    scientificName: "Ovata",
    fileName: "ovata",
    family: "ベンケイソウ科",
    genus: "クラッスラ属",
    notes: "",
    relatedId: [53, 54, 55, 57, 58, 59],
    reading: "ナリキンソウ",
    link: ""
  },
  {
    id: 57,
    name: "縁紅弁慶",
    scientificName: "Ovata",
    fileName: "ovata",
    family: "ベンケイソウ科",
    genus: "クラッスラ属",
    notes: "",
    relatedId: [53, 54, 55, 56, 58, 59],
    reading: "フチベニベンケイ",
    link: ""
  },
  {
    id: 58,
    name: "紅花月",
    scientificName: "Ovata",
    fileName: "ovata",
    family: "ベンケイソウ科",
    genus: "クラッスラ属",
    notes: "",
    relatedId: [53, 54, 55, 56, 57, 59],
    reading: "ベニカゲツ",
    link: ""
  },
  {
    id: 59,
    name: "瑞蝶",
    scientificName: "Ovata",
    fileName: "ovata",
    family: "ベンケイソウ科",
    genus: "クラッスラ属",
    notes: "",
    relatedId: [53, 54, 55, 56, 57, 58],
    reading: "タンチョウ",
    link: ""
  },
  {
    id: 60,
    name: "イーサー",
    scientificName: "Ether",
    fileName: "ether",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [],
    reading: "イーサー",
    link: ""
  },
  {
    id: 61,
    name: "アマビレ",
    scientificName: "Amabile",
    fileName: "amabile",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [],
    reading: "アマビレ",
    link: ""
  },
  {
    id: 62,
    name: "マーガレットレッピン",
    scientificName: "Margarete Reppin",
    fileName: "margarete-reppin",
    family: "ベンケイソウ科",
    genus: "グラプトベリア属",
    notes: "",
    relatedId: [],
    reading: "マーガレットレッピン",
    link: ""
  },
  {
    id: 63,
    name: "紫麗殿",
    scientificName: "Shireiden",
    fileName: "shireiden",
    family: "ベンケイソウ科",
    genus: "パキフィツム属",
    notes: "",
    relatedId: [],
    reading: "シレイデン",
    link: ""
  },
  {
    id: 64,
    name: "斑入りニグラム",
    scientificName: "",
    fileName: "variegated-nigrum",
    family: "サボテン科",
    genus: "ギムノカリキウム属",
    notes: "",
    relatedId: [],
    reading: "フイリニグラム",
    link: "/calcareum-nigrum-cultivation-features/"
  },
  {
    id: 65,
    name: "アンソニー",
    scientificName: "Anthonyi",
    fileName: "anthonyi",
    family: "ベンケイソウ科",
    genus: "ダドレア属",
    notes: "",
    relatedId: [],
    reading: "アンソニー",
    link: ""
  },
  {
    id: 66,
    name: "ダークムーン",
    scientificName: "Dark Moon",
    fileName: "dark-moon",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [],
    reading: "ダークムーン",
    link: ""
  },
  {
    id: 67,
    name: "大和錦",
    scientificName: "Purpusorum",
    fileName: "purpusorum",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [68, 69, 70, 71],
    reading: "ヤマトニシキ",
    link: "/yamato-nishiki-care/"
  },
  {
    id: 68,
    name: "花冠",
    scientificName: "Purpusorum",
    fileName: "purpusorum",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [67, 69, 70, 71],
    reading: "カカン",
    link: "/yamato-nishiki-care/"
  },
  {
    id: 69,
    name: "パープソルム",
    scientificName: "Purpusorum",
    fileName: "purpusorum",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [67, 68, 70, 71],
    reading: "パープソルム",
    link: "/yamato-nishiki-care/"
  },
  {
    id: 70,
    name: "プルプソルム",
    scientificName: "Purpusorum",
    fileName: "purpusorum",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [67, 68, 69, 71],
    reading: "プルプソルム",
    link: "/yamato-nishiki-care/"
  },
  {
    id: 71,
    name: "パプルソラム",
    scientificName: "Purpusorum",
    fileName: "purpusorum",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [67, 68, 69, 70],
    reading: "パプルソラム",
    link: "/yamato-nishiki-care/"
  },
  {
    id: 72,
    name: "オリビア",
    scientificName: "Olivia",
    fileName: "olivia",
    family: "ベンケイソウ科",
    genus: "グラプトベリア属",
    notes: "",
    relatedId: [],
    reading: "オリビア",
    link: ""
  },
  {
    id: 73,
    name: "オンスロー",
    scientificName: "Onslow",
    fileName: "onslow",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [74],
    reading: "オンスロー",
    link: ""
  },
  {
    id: 74,
    name: "オンスロウ",
    scientificName: "Onslow",
    fileName: "onslow",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [73],
    reading: "オンスロウ",
    link: ""
  },
  {
    id: 75,
    name: "月下美人",
    scientificName: "Gekkabijin",
    fileName: "gekkabijin",
    family: "ベンケイソウ科",
    genus: "パキフィツム属",
    notes: "",
    relatedId: [76, 77, 78],
    reading: "ゲッカビジン",
    link: ""
  },
  {
    id: 76,
    name: "月花美人",
    scientificName: "Gekkabijin",
    fileName: "gekkabijin",
    family: "ベンケイソウ科",
    genus: "パキフィツム属",
    notes: "",
    relatedId: [75, 77, 78],
    reading: "ゲッカビジン",
    link: ""
  },
  {
    id: 77,
    name: "見返り美人",
    scientificName: "Gekkabijin",
    fileName: "gekkabijin",
    family: "ベンケイソウ科",
    genus: "パキフィツム属",
    notes: "",
    relatedId: [75, 76, 78],
    reading: "ミカエリビジン",
    link: ""
  },
  {
    id: 78,
    name: "ウォルファ美人",
    scientificName: "Gekkabijin",
    fileName: "gekkabijin",
    family: "ベンケイソウ科",
    genus: "パキフィツム属",
    notes: "",
    relatedId: [75, 76, 77],
    reading: "ウォルファビジン",
    link: ""
  },
  {
    id: 79,
    name: "クラバツム",
    scientificName: "Clavatum",
    fileName: "clavatum",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [80],
    reading: "クラバツム",
    link: ""
  },
  {
    id: 80,
    name: "ラウム",
    scientificName: "Clavatum",
    fileName: "clavatum",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [79],
    reading: "ラウム",
    link: ""
  },
  {
    id: 81,
    name: "ムーンガドニス",
    scientificName: "Esther",
    fileName: "esther",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [82, 83, 84, 85, 86, 87],
    reading: "ムーンガドニス",
    link: ""
  },
  {
    id: 82,
    name: "エスター",
    scientificName: "Esther",
    fileName: "esther",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [81, 83, 84, 85, 86, 87],
    reading: "エスター",
    link: ""
  },
  {
    id: 83,
    name: "魅惑の月",
    scientificName: "Esther",
    fileName: "esther",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [81, 82, 84, 85, 86, 87],
    reading: "ミワクノツキ",
    link: ""
  },
  {
    id: 84,
    name: "織姫",
    scientificName: "Esther",
    fileName: "esther",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [81, 82, 83, 85, 86, 87],
    reading: "オリヒメ",
    link: ""
  },
  {
    id: 85,
    name: "月光女神",
    scientificName: "Esther",
    fileName: "esther",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [81, 82, 83, 84, 86, 87],
    reading: "ゲッコウメガミ",
    link: ""
  },
  {
    id: 86,
    name: "エッシャー",
    scientificName: "Esther",
    fileName: "esther",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [81, 82, 83, 84, 85, 87],
    reading: "エッシャー",
    link: ""
  },
  {
    id: 87,
    name: "ムーンガッデス",
    scientificName: "Esther",
    fileName: "esther",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [81, 82, 83, 84, 85, 86],
    reading: "ムーンガッデス",
    link: ""
  },
  {
    id: 88,
    name: "キュービックフロスト",
    scientificName: "Cubic Frost",
    fileName: "cubic-frost",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [89],
    reading: "キュービックフロスト",
    link: ""
  },
  {
    id: 89,
    name: "キュービックフロスティ",
    scientificName: "Cubic Frost",
    fileName: "cubic-frost",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [88],
    reading: "キュービックフロスティ",
    link: ""
  },
  {
    id: 90,
    name: "クラウディア",
    scientificName: "Claudia",
    fileName: "claudia",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [91],
    reading: "クラウディア",
    link: ""
  },
  {
    id: 91,
    name: "クローディア",
    scientificName: "Claudia",
    fileName: "claudia",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [90],
    reading: "クローディア",
    link: ""
  },
  {
    id: 92,
    name: "サブセシリス",
    scientificName: "Echeveria peacockii 'Subsessilis'",
    fileName: "echeveria-peacockii-subsessilis",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [93, 94, 95],
    reading: "サブセシリス",
    link: ""
  },
  {
    id: 93,
    name: "ピーコッキー",
    scientificName: "Echeveria peacockii 'Subsessilis'",
    fileName: "echeveria-peacockii-subsessilis",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [92, 94, 95],
    reading: "ピーコッキー",
    link: ""
  },
  {
    id: 94,
    name: "養老",
    scientificName: "Echeveria peacockii 'Subsessilis'",
    fileName: "echeveria-peacockii-subsessilis",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [92, 93, 95],
    reading: "ヨウロウ",
    link: ""
  },
  {
    id: 95,
    name: "ピーコッキー・サブセシリス",
    scientificName: "Echeveria peacockii 'Subsessilis'",
    fileName: "echeveria-peacockii-subsessilis",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [92, 93, 94],
    reading: "ピーコッキー・サブセシリス",
    link: ""
  },
  {
    id: 96,
    name: "ブルーアップル",
    scientificName: "Echeveria 'Blue Apple'",
    fileName: "echeveria-blue-apple",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [],
    reading: "ブルーアップル",
    link: ""
  },
  {
    id: 97,
    name: "ヌダ",
    scientificName: "Echeveria nuda",
    fileName: "echeveria-nuda",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [],
    reading: "ヌダ",
    link: ""
  },
  {
    id: 98,
    name: "七福美尼",
    scientificName: "Shichifuku-bini",
    fileName: "shichifuku-bini",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [99],
    reading: "シチフクビニ",
    link: ""
  },
  {
    id: 99,
    name: "七福ミニ",
    scientificName: "Shichifuku-bini",
    fileName: "shichifuku-bini",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [98],
    reading: "シチフクミニ",
    link: ""
  },
  {
    id: 100,
    name: "新玉つづり",
    scientificName: "Burrito",
    fileName: "burrito",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [101, 102, 103],
    reading: "アラタマツヅリ",
    link: ""
  },
  {
    id: 101,
    name: "ビアーホップ",
    scientificName: "Burrito",
    fileName: "burrito",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [100, 102, 103],
    reading: "ビアーホップ",
    link: ""
  },
  {
    id: 102,
    name: "姫玉綴り",
    scientificName: "Burrito",
    fileName: "burrito",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [100, 101, 103],
    reading: "ヒメタマツヅリ",
    link: ""
  },
  {
    id: 103,
    name: "うさぎのかくれんぼ",
    scientificName: "Burrito",
    fileName: "burrito",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [100, 101, 102],
    reading: "ウサギノカクレンボ",
    link: ""
  },
  {
    id: 104,
    name: "天人の舞",
    scientificName: "Kalanchoe orgyalis",
    fileName: "kalanchoe-orgyalis",
    family: "ベンケイソウ科",
    genus: "カランコエ属",
    notes: "",
    relatedId: [105, 106, 107, 108, 109],
    reading: "テンニンノマイ",
    link: "/senningarden-tips/"
  },
  {
    id: 105,
    name: "仙人の舞",
    scientificName: "Kalanchoe orgyalis",
    fileName: "kalanchoe-orgyalis",
    family: "ベンケイソウ科",
    genus: "カランコエ属",
    notes: "",
    relatedId: [104, 106, 107, 108, 109],
    reading: "センニンノマイ",
    link: "/senningarden-tips/"
  },
  {
    id: 106,
    name: "オルギアリス",
    scientificName: "Kalanchoe orgyalis",
    fileName: "kalanchoe-orgyalis",
    family: "ベンケイソウ科",
    genus: "カランコエ属",
    notes: "",
    relatedId: [104, 105, 107, 108, 109],
    reading: "オルギアリス",
    link: "/senningarden-tips/"
  },
  {
    id: 107,
    name: "金の卵",
    scientificName: "Kalanchoe orgyalis",
    fileName: "kalanchoe-orgyalis",
    family: "ベンケイソウ科",
    genus: "カランコエ属",
    notes: "",
    relatedId: [104, 105, 106, 108, 109],
    reading: "キンノタマゴ",
    link: "/senningarden-tips/"
  },
  {
    id: 108,
    name: "銀の卵",
    scientificName: "Kalanchoe orgyalis",
    fileName: "kalanchoe-orgyalis",
    family: "ベンケイソウ科",
    genus: "カランコエ属",
    notes: "",
    relatedId: [104, 105, 106, 107, 109],
    reading: "ギンノタマゴ",
    link: "/senningarden-tips/"
  },
  {
    id: 109,
    name: "仙人の扇",
    scientificName: "Kalanchoe orgyalis",
    fileName: "kalanchoe-orgyalis",
    family: "ベンケイソウ科",
    genus: "カランコエ属",
    notes: "",
    relatedId: [104, 105, 106, 107, 108],
    reading: "センニンノオウギ",
    link: "/senningarden-tips/"
  },
  {
    id: 110,
    name: "サンライズマム",
    scientificName: "Sunrise Mom",
    fileName: "sunrise-mom",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [111, 112],
    reading: "サンライズマム",
    link: ""
  },
  {
    id: 111,
    name: "イエロームーン",
    scientificName: "Sunrise Mom",
    fileName: "sunrise-mom",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [110, 112],
    reading: "イエロームーン",
    link: ""
  },
  {
    id: 112,
    name: "新立田",
    scientificName: "Sunrise Mom",
    fileName: "sunrise-mom",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [110, 111],
    reading: "シンタツタ",
    link: ""
  },
  {
    id: 113,
    name: "シャビアナ",
    scientificName: "Shaviana",
    fileName: "shaviana",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [114, 115],
    reading: "シャビアナ",
    link: "/kalanchoe-tomentosa-beauty-and-care-guide/"
  },
  {
    id: 114,
    name: "祇園の舞",
    scientificName: "Shaviana",
    fileName: "shaviana",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [113, 115],
    reading: "ギオンノマイ",
    link: "/kalanchoe-tomentosa-beauty-and-care-guide/"
  },
  {
    id: 115,
    name: "サウィアナ",
    scientificName: "Shaviana",
    fileName: "shaviana",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [113, 114],
    reading: "サウィアナ",
    link: "/kalanchoe-tomentosa-beauty-and-care-guide/"
  },
  {
    id: 116,
    name: "シルバースター",
    scientificName: "Silver Star",
    fileName: "silver-star",
    family: "ベンケイソウ科",
    genus: "グラプトベリア属",
    notes: "",
    relatedId: [],
    reading: "シルバースター",
    link: ""
  },
  {
    id: 117,
    name: "秋麗",
    scientificName: "Francesco Baldi",
    fileName: "francesco-baldi",
    family: "ベンケイソウ科",
    genus: "グラプトセダム属",
    notes: "",
    relatedId: [118],
    reading: "シュウレイ",
    link: ""
  },
  {
    id: 118,
    name: "フランケスコバルディ",
    scientificName: "Francesco Baldi",
    fileName: "francesco-baldi",
    family: "ベンケイソウ科",
    genus: "グラプトセダム属",
    notes: "",
    relatedId: [117],
    reading: "フランケスコバルディ",
    link: ""
  },
  {
    id: 119,
    name: "シャンハイローズ",
    scientificName: "Shanghai Rose",
    fileName: "shanghai-rose",
    family: "ベンケイソウ科",
    genus: "センペルビブム属",
    notes: "",
    relatedId: [],
    reading: "シャンハイローズ",
    link: ""
  },
  {
    id: 120,
    name: "上海ローズ",
    scientificName: "Shanghai Rose",
    fileName: "shanghai-rose",
    family: "ベンケイソウ科",
    genus: "センペルビブム属",
    notes: "",
    relatedId: [],
    reading: "シャンハイローズ",
    link: ""
  },
  {
    id: 121,
    name: "ジャシリー",
    scientificName: "Jasiri",
    fileName: "jasiri",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [],
    reading: "ジャシリー",
    link: ""
  },
  {
    id: 122,
    name: "ゴールデングロウ（エケベリア属）",
    scientificName: "Echeveria 'Golden Glow'",
    fileName: "echeveria-golden-glow",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [123],
    reading: "ゴールデングロウ",
    link: ""
  },
  {
    id: 123,
    name: "ゴールデングロー（エケベリア属）",
    scientificName: "Echeveria 'Golden Glow'",
    fileName: "echeveria-golden-glow",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [122],
    reading: "ゴールデングロー",
    link: ""
  },
  {
    id: 124,
    name: "ジョニーウォーカー",
    scientificName: "Echeveria 'Johnnie Walker'",
    fileName: "echeveria-johnnie-walker",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [],
    reading: "ジョニーウォーカー",
    link: ""
  },
  {
    id: 125,
    name: "恋心",
    scientificName: "Sedum 'Koigokoro'",
    fileName: "sedum-koigokoro",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [],
    reading: "コイゴコロ",
    link: "/love-and-romance-in-the-world-of-succulents/"
  },
  {
    id: 126,
    name: "グリムワン",
    scientificName: "Graptoveria 'A Grim One'",
    fileName: "graptoveria-a-grim-one",
    family: "ベンケイソウ科",
    genus: "グラプトベリア属",
    notes: "",
    relatedId: [127, 128],
    reading: "グリムワン",
    link: "/grimone-artful-leaves/"
  },
  {
    id: 127,
    name: "エイグリーワン",
    scientificName: "Graptoveria 'A Grim One'",
    fileName: "graptoveria-a-grim-one",
    family: "ベンケイソウ科",
    genus: "グラプトベリア属",
    notes: "",
    relatedId: [126, 128],
    reading: "エイグリーワン",
    link: "/grimone-artful-leaves/"
  },
  {
    id: 128,
    name: "エイグリムワン",
    scientificName: "Graptoveria 'A Grim One'",
    fileName: "graptoveria-a-grim-one",
    family: "ベンケイソウ科",
    genus: "グラプトベリア属",
    notes: "",
    relatedId: [126, 127],
    reading: "エイグリムワン",
    link: "/grimone-artful-leaves/"
  },
  {
    id: 129,
    name: "ブラックローズ",
    scientificName: "Echeveria 'Black Rose'",
    fileName: "echeveria-black-rose",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [130],
    reading: "ブラックローズ",
    link: ""
  },
  {
    id: 130,
    name: "黒バラ",
    scientificName: "Echeveria 'Black Rose'",
    fileName: "echeveria-black-rose",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [129],
    reading: "クロバラ",
    link: ""
  },
  {
    id: 131,
    name: "子持ち蓮華",
    scientificName: "Orostachys bohmeri",
    fileName: "orostachys-bohmeri",
    family: "ベンケイソウ科",
    genus: "オロスタキス属",
    notes: "",
    relatedId: [132],
    reading: "コモチレンゲ",
    link: ""
  },
  {
    id: 132,
    name: "子持蓮華",
    scientificName: "Orostachys bohmeri",
    fileName: "orostachys-bohmeri",
    family: "ベンケイソウ科",
    genus: "オロスタキス属",
    notes: "",
    relatedId: [131],
    reading: "コモチレンゲ",
    link: ""
  },
  {
    id: 133,
    name: "ティッピー",
    scientificName: "Echeveria 'Tippy'",
    fileName: "echeveria-tippy",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [134],
    reading: "ティッピー",
    link: ""
  },
  {
    id: 134,
    name: "テイピ",
    scientificName: "Echeveria 'Tippy'",
    fileName: "echeveria-tippy",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [133],
    reading: "テイピ",
    link: ""
  },
  {
    id: 135,
    name: "デビー",
    scientificName: "Graptoveria 'Debbi'",
    fileName: "graptoveria-debbi",
    family: "ベンケイソウ科",
    genus: "グラプトベリア属",
    notes: "",
    relatedId: [136, 137],
    reading: "デビー",
    link: ""
  },
  {
    id: 136,
    name: "パープルクイーン",
    scientificName: "Graptoveria 'Debbi'",
    fileName: "graptoveria-debbi",
    family: "ベンケイソウ科",
    genus: "グラプトベリア属",
    notes: "",
    relatedId: [135, 137],
    reading: "パープルクイーン",
    link: ""
  },
  {
    id: 137,
    name: "グラプトベリア・デビー",
    scientificName: "Graptoveria 'Debbi'",
    fileName: "graptoveria-debbi",
    family: "ベンケイソウ科",
    genus: "グラプトベリア属",
    notes: "",
    relatedId: [135, 136],
    reading: "グラプトベリア・デビー",
    link: ""
  },
  {
    id: 138,
    name: "トップシータービー",
    scientificName: "Echeveria runyonii 'Topsy Turvy'",
    fileName: "echeveria-runyonii-topsy-turvy",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [139, 140, 141, 142, 143, 144],
    reading: "トップシータービー",
    link: ""
  },
  {
    id: 139,
    name: "トップスプレンダー",
    scientificName: "Echeveria runyonii 'Topsy Turvy'",
    fileName: "echeveria-runyonii-topsy-turvy",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [138, 140, 141, 142, 143, 144],
    reading: "トップスプレンダー",
    link: ""
  },
  {
    id: 140,
    name: "トプシータービー",
    scientificName: "Echeveria runyonii 'Topsy Turvy'",
    fileName: "echeveria-runyonii-topsy-turvy",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [138, 139, 141, 142, 143, 144],
    reading: "トプシータービー",
    link: ""
  },
  {
    id: 141,
    name: "ルンヨニー",
    scientificName: "Echeveria runyonii 'Topsy Turvy'",
    fileName: "echeveria-runyonii-topsy-turvy",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [138, 139, 140, 142, 143, 144],
    reading: "ルンヨニー",
    link: ""
  },
  {
    id: 142,
    name: "トプシーツルビー",
    scientificName: "Echeveria runyonii 'Topsy Turvy'",
    fileName: "echeveria-runyonii-topsy-turvy",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [138, 139, 140, 141, 143, 144],
    reading: "トプシーツルビー",
    link: ""
  },
  {
    id: 143,
    name: "トプシーツルヴィ",
    scientificName: "Echeveria runyonii 'Topsy Turvy'",
    fileName: "echeveria-runyonii-topsy-turvy",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [138, 139, 140, 141, 142, 144],
    reading: "トプシーツルヴィ",
    link: ""
  },
  {
    id: 144,
    name: "トプシー・ターヴィー",
    scientificName: "Echeveria runyonii 'Topsy Turvy'",
    fileName: "echeveria-runyonii-topsy-turvy",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [138, 139, 140, 141, 142, 143],
    reading: "トプシー・ターヴィー",
    link: ""
  },
  {
    id: 145,
    name: "だるま秀麗",
    scientificName: "Graptopetalum 'Daruma Shuurei'",
    fileName: "graptopetalum-daruma-shuurei",
    family: "ベンケイソウ科",
    genus: "グラプトペタルム属",
    notes: "",
    relatedId: [146, 147],
    reading: "ダルマシュウレイ",
    link: ""
  },
  {
    id: 146,
    name: "だるま秋麗",
    scientificName: "Graptopetalum 'Daruma Shuurei'",
    fileName: "graptopetalum-daruma-shuurei",
    family: "ベンケイソウ科",
    genus: "グラプトペタルム属",
    notes: "",
    relatedId: [145, 147],
    reading: "ダルマシュウレイ",
    link: ""
  },
  {
    id: 147,
    name: "達磨秀麗",
    scientificName: "Graptopetalum 'Daruma Shuurei'",
    fileName: "graptopetalum-daruma-shuurei",
    family: "ベンケイソウ科",
    genus: "グラプトペタルム属",
    notes: "",
    relatedId: [145, 146],
    reading: "ダルマシュウレイ",
    link: ""
  },
  {
    id: 148,
    name: "虹の玉",
    scientificName: "Sedum rubrotinctum",
    fileName: "sedum-rubrotinctum",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [149],
    reading: "ニジノタマ",
    link: ""
  },
  {
    id: 149,
    name: "ラブロティングダム",
    scientificName: "Sedum rubrotinctum",
    fileName: "sedum-rubrotinctum",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [148],
    reading: "ラブロティングダム",
    link: ""
  },
  {
    id: 150,
    name: "爪蓮華",
    scientificName: "Orostachys japonica",
    fileName: "orostachys-japonica",
    family: "ベンケイソウ科",
    genus: "オロスタキス属",
    notes: "",
    relatedId: [],
    reading: "ツメレンゲ",
    link: "/sedum-lineare-male-perennial/"
  },
  {
    id: 151,
    name: "ダスティローズ",
    scientificName: "Echeveria 'Dusty Rose'",
    fileName: "echeveria-dusty-rose",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [152],
    reading: "ダスティローズ",
    link: ""
  },
  {
    id: 152,
    name: "ダスキーローズ",
    scientificName: "Echeveria 'Dusty Rose'",
    fileName: "echeveria-dusty-rose",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [151],
    reading: "ダスキーローズ",
    link: ""
  },
  {
    id: 153,
    name: "レズリー",
    scientificName: "Echeveria 'Rezry'",
    fileName: "echeveria-rezry",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [],
    reading: "レズリー",
    link: ""
  },
  {
    id: 154,
    name: "ラウ030",
    scientificName: "Echeveria subcorymbosa",
    fileName: "echeveria-subcorymbosa",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [155, 156, 157],
    reading: "ラウ030",
    link: ""
  },
  {
    id: 155,
    name: "サブコリーボサ",
    scientificName: "Echeveria subcorymbosa",
    fileName: "echeveria-subcorymbosa",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [154, 156, 157],
    reading: "サブコリーボサ",
    link: ""
  },
  {
    id: 156,
    name: "サブコリンボサ",
    scientificName: "Echeveria subcorymbosa",
    fileName: "echeveria-subcorymbosa",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [154, 155, 157],
    reading: "サブコリンボサ",
    link: ""
  },
  {
    id: 157,
    name: "エクスパルチカ",
    scientificName: "Echeveria subcorymbosa",
    fileName: "echeveria-subcorymbosa",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [154, 155, 156],
    reading: "エクスパルチカ",
    link: ""
  },
  {
    id: 158,
    name: "ラブリーローズ",
    scientificName: "Echeveria 'Lovely Rose'",
    fileName: "echeveria-lovely-rose",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [],
    reading: "ラブリーローズ",
    link: "/echeveria-lovely-rose-care-guide/"
  },
  {
    id: 159,
    name: "リトルビューティ",
    scientificName: "Graptosedum 'Little Beauty'",
    fileName: "graptosedum-little-beauty",
    family: "ベンケイソウ科",
    genus: "グラプトセダム属",
    notes: "",
    relatedId: [],
    reading: "リトルビューティ",
    link: ""
  },
  {
    id: 160,
    name: "マンドリースクラール",
    scientificName: "Haworthia 'Mandriscrar'",
    fileName: "haworthia-mandriscrar",
    family: "キジカクシ科ツルボラン亜科",
    genus: "ハオルチア属",
    notes: "",
    relatedId: [],
    reading: "マンドリースクラール",
    link: ""
  },
  {
    id: 161,
    name: "大和美尼",
    scientificName: "Echeveria 'Yamatobini'",
    fileName: "echeveria-yamatobini",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [],
    reading: "ヤマトビニ",
    link: "/yamato-bini/"
  },
  {
    id: 162,
    name: "レディジア",
    scientificName: "Sedeveria 'Letizia'",
    fileName: "sedeveria-letizia",
    family: "ベンケイソウ科",
    genus: "セデベリア属",
    notes: "",
    relatedId: [163, 164],
    reading: "レディジア",
    link: ""
  },
  {
    id: 163,
    name: "レティジア",
    scientificName: "Sedeveria 'Letizia'",
    fileName: "sedeveria-letizia",
    family: "ベンケイソウ科",
    genus: "セデベリア属",
    notes: "",
    relatedId: [162, 164],
    reading: "レティジア",
    link: ""
  },
  {
    id: 164,
    name: "万華鏡",
    scientificName: "Sedeveria 'Letizia'",
    fileName: "sedeveria-letizia",
    family: "ベンケイソウ科",
    genus: "セデベリア属",
    notes: "",
    relatedId: [162, 163],
    reading: "マンゲキョウ",
    link: ""
  },
  {
    id: 165,
    name: "レッドベルベット",
    scientificName: "Echeveria 'Red Velvet'",
    fileName: "echeveria-red-velvet",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [],
    reading: "レッドベルベット",
    link: ""
  },
  {
    id: 166,
    name: "ラウリンゼ",
    scientificName: "Echeveria 'Laulindsa'",
    fileName: "echeveria-laulindsa",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [167],
    reading: "ラウリンゼ",
    link: ""
  },
  {
    id: 167,
    name: "ラウィーリンゼ",
    scientificName: "Echeveria 'Laulindsa'",
    fileName: "echeveria-laulindsa",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [166],
    reading: "ラウィーリンゼ",
    link: ""
  },
  {
    id: 168,
    name: "ロゲルシー",
    scientificName: "Crassula rogersii",
    fileName: "crassula-rogersii",
    family: "ベンケイソウ科",
    genus: "クラッスラ属",
    notes: "",
    relatedId: [169, 170],
    reading: "ロゲルシー",
    link: ""
  },
  {
    id: 169,
    name: "ロゲルシー斑入り",
    scientificName: "Crassula rogersii",
    fileName: "crassula-rogersii",
    family: "ベンケイソウ科",
    genus: "クラッスラ属",
    notes: "",
    relatedId: [168, 170],
    reading: "ロゲルシーフイリ",
    link: ""
  },
  {
    id: 170,
    name: "ロゲルシー(斑入り)",
    scientificName: "Crassula rogersii",
    fileName: "crassula-rogersii",
    family: "ベンケイソウ科",
    genus: "クラッスラ属",
    notes: "",
    relatedId: [168, 169],
    reading: "ロゲルシーフイリ",
    link: ""
  },
  {
    id: 171,
    name: "レッドベリー",
    scientificName: "Sedum rubrotinctum 'Red Berry'",
    fileName: "sedum-rubrotinctum-red-berry",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [],
    reading: "レッドベリー",
    link: ""
  },
  {
    id: 172,
    name: "モラン",
    scientificName: "Echeveria 'Molan'",
    fileName: "echeveria-molan",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [],
    reading: "モラン",
    link: ""
  },
  {
    id: 173,
    name: "マリリン（エケベリア属）",
    scientificName: "Echeveria 'Marilyn Henderson'",
    fileName: "echeveria-marilyn-henderson",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [],
    reading: "マリリン",
    link: ""
  },
  {
    id: 174,
    name: "マクドガリー（グラプトペタルム属）",
    scientificName: "Graptopetalum macdougallii",
    fileName: "graptopetalum-macdougallii",
    family: "ベンケイソウ科",
    genus: "グラプトペタルム属",
    notes: "",
    relatedId: [],
    reading: "マクドガリー",
    link: ""
  },
  {
    id: 175,
    name: "紅葉祭り",
    scientificName: "Crassula capitella 'Trefu'",
    fileName: "crassula-capitella-trefu",
    family: "ベンケイソウ科",
    genus: "クラッスラ属",
    notes: "",
    relatedId: [176, 177],
    reading: "モミジマツリ",
    link: ""
  },
  {
    id: 176,
    name: "モミジマツリ",
    scientificName: "Crassula capitella 'Trefu'",
    fileName: "crassula-capitella-trefu",
    family: "ベンケイソウ科",
    genus: "クラッスラ属",
    notes: "",
    relatedId: [175, 177],
    reading: "モミジマツリ",
    link: ""
  },
  {
    id: 177,
    name: "紅葉祭",
    scientificName: "Crassula capitella 'Trefu'",
    fileName: "crassula-capitella-trefu",
    family: "ベンケイソウ科",
    genus: "クラッスラ属",
    notes: "",
    relatedId: [175, 176],
    reading: "モミジマツリ",
    link: ""
  },
  {
    id: 178,
    name: "女雛",
    scientificName: "Echeveria 'Mebina'",
    fileName: "echeveria-mebina",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [179],
    reading: "メビナ",
    link: ""
  },
  {
    id: 179,
    name: "メビナ",
    scientificName: "Echeveria 'Mebina'",
    fileName: "echeveria-mebina",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [178],
    reading: "メビナ",
    link: ""
  },
  {
    id: 180,
    name: "ミニマハイブリッド",
    scientificName: "Echeveria 'Minima Hybrid'",
    fileName: "echeveria-minima-hybrid",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [],
    reading: "ミニマハイブリッド",
    link: ""
  },
  {
    id: 181,
    name: "桃太郎",
    scientificName: "Echeveria 'Momotaro'",
    fileName: "echeveria-momotaro",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [182, 183, 184],
    reading: "モモタロウ",
    link: "/graptosedum-francesco-baldi/"
  },
  {
    id: 182,
    name: "チワワリンゼ",
    scientificName: "Echeveria 'Momotaro'",
    fileName: "echeveria-momotaro",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [181, 183, 184],
    reading: "チワワリンゼ",
    link: "/graptosedum-francesco-baldi/"
  },
  {
    id: 183,
    name: "ベアトリス",
    scientificName: "Echeveria 'Momotaro'",
    fileName: "echeveria-momotaro",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [181, 182, 184],
    reading: "ベアトリス",
    link: "/graptosedum-francesco-baldi/"
  },
  {
    id: 184,
    name: "ベアトリーチェ",
    scientificName: "Echeveria 'Momotaro'",
    fileName: "echeveria-momotaro",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [181, 182, 183],
    reading: "ベアトリーチェ",
    link: "/graptosedum-francesco-baldi/"
  },
  {
    id: 185,
    name: "メラコ",
    scientificName: "Echeveria 'Melaco'",
    fileName: "echeveria-melaco",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [],
    reading: "メラコ",
    link: ""
  },
  {
    id: 186,
    name: "巻絹",
    scientificName: "Sempervivum arachnoideum",
    fileName: "sempervivum-arachnoideum",
    family: "ベンケイソウ科",
    genus: "センペルビブム属",
    notes: "",
    relatedId: [187, 188, 189],
    reading: "マキケン",
    link: ""
  },
  {
    id: 187,
    name: "クモノスバンダイソウ",
    scientificName: "Sempervivum arachnoideum",
    fileName: "sempervivum-arachnoideum",
    family: "ベンケイソウ科",
    genus: "センペルビブム属",
    notes: "",
    relatedId: [186, 188, 189],
    reading: "クモノスバンダイソウ",
    link: ""
  },
  {
    id: 188,
    name: "アラクノイデウム",
    scientificName: "Sempervivum arachnoideum",
    fileName: "sempervivum-arachnoideum",
    family: "ベンケイソウ科",
    genus: "センペルビブム属",
    notes: "",
    relatedId: [186, 187, 189],
    reading: "アラクノイデウム",
    link: ""
  },
  {
    id: 189,
    name: "蜘蛛巣万代草",
    scientificName: "Sempervivum arachnoideum",
    fileName: "sempervivum-arachnoideum",
    family: "ベンケイソウ科",
    genus: "センペルビブム属",
    notes: "",
    relatedId: [186, 187, 188],
    reading: "クモノスバンダイソウ",
    link: ""
  },
  {
    id: 190,
    name: "斑入りベビーサンローズ",
    scientificName: "",
    fileName: "variegated-aptenia-cordifolia-f-variegata",
    family: "ハマミズナ科",
    genus: "アプテニア属",
    notes: "",
    relatedId: [],
    reading: "フイリベビーサンローズ",
    link: ""
  },
  {
    id: 191,
    name: "ロジャージョーンズ",
    scientificName: "Pachyveria 'Roger Jones'",
    fileName: "pachyveria-roger-jones",
    family: "ベンケイソウ科",
    genus: "パキベリア属",
    notes: "",
    relatedId: [],
    reading: "ロジャージョーンズ",
    link: ""
  },
  {
    id: 192,
    name: "ルシンダ",
    scientificName: "Echeveria 'Lucinda'",
    fileName: "echeveria-lucinda",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [],
    reading: "ルシンダ",
    link: ""
  },
  {
    id: 193,
    name: "大和の薔薇",
    scientificName: "Echeveria 'Yamato-no-bara'",
    fileName: "echeveria-yamato-no-bara",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [],
    reading: "ヤマトノバラ",
    link: ""
  },
  {
    id: 194,
    name: "マッコス",
    scientificName: "Echeveria 'Marcus'",
    fileName: "echeveria-marcus",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [195, 196, 197],
    reading: "マッコス",
    link: ""
  },
  {
    id: 195,
    name: "マルクス",
    scientificName: "Echeveria 'Marcus'",
    fileName: "echeveria-marcus",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [194, 196, 197],
    reading: "マルクス",
    link: ""
  },
  {
    id: 196,
    name: "マルコス",
    scientificName: "Echeveria 'Marcus'",
    fileName: "echeveria-marcus",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [194, 195, 197],
    reading: "マルコス",
    link: ""
  },
  {
    id: 197,
    name: "アーリーデイト",
    scientificName: "Echeveria 'Marcus'",
    fileName: "echeveria-marcus",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [194, 195, 196],
    reading: "アーリーデイト",
    link: ""
  },
  {
    id: 198,
    name: "ビクターケーン",
    scientificName: "Graptopetalum 'Victor Kane'",
    fileName: "graptopetalum-victor-kane",
    family: "ベンケイソウ科",
    genus: "グラプトペタルム属",
    notes: "",
    relatedId: [199],
    reading: "ビクターケーン",
    link: ""
  },
  {
    id: 199,
    name: "初想",
    scientificName: "Graptopetalum 'Victor Kane'",
    fileName: "graptopetalum-victor-kane",
    family: "ベンケイソウ科",
    genus: "グラプトペタルム属",
    notes: "",
    relatedId: [198],
    reading: "ハツオモイ",
    link: ""
  },
  {
    id: 200,
    name: "バッシュフル",
    scientificName: "Graptoveria 'Pinkle Ruby'",
    fileName: "graptoveria-pinkle-ruby",
    family: "ベンケイソウ科",
    genus: "グラプトベリア属",
    notes: "",
    relatedId: [12, 13, 201],
    reading: "バッシュフル",
    link: ""
  },
  {
    id: 201,
    name: "ジュジュベ",
    scientificName: "Graptoveria 'Pinkle Ruby'",
    fileName: "graptoveria-pinkle-ruby",
    family: "ベンケイソウ科",
    genus: "グラプトベリア属",
    notes: "",
    relatedId: [12, 13, 200],
    reading: "ジュジュベ",
    link: ""
  },
  {
    id: 202,
    name: "銀紅蓮",
    scientificName: "Graptoveria 'Caerulescens'",
    fileName: "graptoveria-caerulescens",
    family: "ベンケイソウ科",
    genus: "グラプトベリア属",
    notes: "",
    relatedId: [4, 203],
    reading: "ギンコウレン",
    link: "/echeveria-battle-whitepeony-vs-lightice/"
  },
  {
    id: 203,
    name: "姫朧月",
    scientificName: "Graptoveria 'Caerulescens'",
    fileName: "graptoveria-caerulescens",
    family: "ベンケイソウ科",
    genus: "グラプトベリア属",
    notes: "",
    relatedId: [4, 202],
    reading: "ヒメオボロヅキ",
    link: "/echeveria-battle-whitepeony-vs-lightice/"
  },
  {
    id: 204,
    name: "春萌",
    scientificName: "Sedum 'Alice Evans'",
    fileName: "sedum-alice-evans",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [205, 206],
    reading: "ハルモエ",
    link: ""
  },
  {
    id: 205,
    name: "アリス",
    scientificName: "Sedum 'Alice Evans'",
    fileName: "sedum-alice-evans",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [204, 206],
    reading: "アリス",
    link: ""
  },
  {
    id: 206,
    name: "エヴァンス",
    scientificName: "Sedum 'Alice Evans'",
    fileName: "sedum-alice-evans",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [204, 205],
    reading: "エヴァンス",
    link: ""
  },
  {
    id: 207,
    name: "樹氷",
    scientificName: "Sedeveria 'Soft Rime'",
    fileName: "sedeveria-soft-rime",
    family: "ベンケイソウ科",
    genus: "セデベリア属",
    notes: "",
    relatedId: [208, 209],
    reading: "ジュヒョウ",
    link: ""
  },
  {
    id: 208,
    name: "ソフトライム",
    scientificName: "Sedeveria 'Soft Rime'",
    fileName: "sedeveria-soft-rime",
    family: "ベンケイソウ科",
    genus: "セデベリア属",
    notes: "",
    relatedId: [],
    reading: "ソフトライム",
    link: ""
  },
  {
    id: 209,
    name: "パープルパール",
    scientificName: "Echeveria 'Purple Pearl'",
    fileName: "echeveria-purple-pearl",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [],
    reading: "パープルパール",
    link: ""
  },
  {
    id: 210,
    name: "ハムシー",
    scientificName: "Echeveria harmsii",
    fileName: "echeveria-harmsii",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [211, 212, 213, 214, 215],
    reading: "ハムシー",
    link: ""
  },
  {
    id: 211,
    name: "花の司",
    scientificName: "Echeveria harmsii",
    fileName: "echeveria-harmsii",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [210, 212, 213, 214, 215],
    reading: "ハナノツカサ",
    link: ""
  },
  {
    id: 212,
    name: "ハルムシー",
    scientificName: "Echeveria harmsii",
    fileName: "echeveria-harmsii",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [210, 211, 213, 214, 215],
    reading: "ハルムシー",
    link: ""
  },
  {
    id: 213,
    name: "錦の司",
    scientificName: "Echeveria harmsii",
    fileName: "echeveria-harmsii",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [210, 211, 212, 214, 215],
    reading: "ニシキノツカサ",
    link: ""
  },
  {
    id: 214,
    name: "花司",
    scientificName: "Echeveria harmsii",
    fileName: "echeveria-harmsii",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [210, 211, 212, 213, 215],
    reading: "ハナツカサ",
    link: ""
  },
  {
    id: 215,
    name: "ハームシー",
    scientificName: "Echeveria harmsii",
    fileName: "echeveria-harmsii",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [210, 211, 212, 213, 214],
    reading: "ハームシー",
    link: ""
  },
  {
    id: 216,
    name: "紅司",
    scientificName: "Echeveria nodulosa",
    fileName: "echeveria-nodulosa",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [],
    reading: "ベニツカサ",
    link: ""
  },
  {
    id: 217,
    name: "桜牡丹",
    scientificName: "Graptosedum 'Ghosty'",
    fileName: "graptosedum-ghosty",
    family: "ベンケイソウ科",
    genus: "グラプトセダム属",
    notes: "",
    relatedId: [218, 219],
    reading: "サクラボタン",
    link: ""
  },
  {
    id: 218,
    name: "ゴースティ",
    scientificName: "Graptosedum 'Ghosty'",
    fileName: "graptosedum-ghosty",
    family: "ベンケイソウ科",
    genus: "グラプトセダム属",
    notes: "",
    relatedId: [217, 219],
    reading: "ゴースティ",
    link: ""
  },
  {
    id: 219,
    name: "ゴースティン",
    scientificName: "Graptosedum 'Ghosty'",
    fileName: "graptosedum-ghosty",
    family: "ベンケイソウ科",
    genus: "グラプトセダム属",
    notes: "",
    relatedId: [217, 218],
    reading: "ゴースティン",
    link: ""
  },
  {
    id: 220,
    name: "ピンクプリティ",
    scientificName: "Echeveria 'Pink Pretty'",
    fileName: "echeveria-pink-pretty",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [],
    reading: "ピンクプリティ",
    link: ""
  },
  {
    id: 221,
    name: "紅稚児",
    scientificName: "Crassula pubescens ssp.radicans",
    fileName: "crassula-pubescens-ssp-radicans",
    family: "ベンケイソウ科",
    genus: "クラッスラ属",
    notes: "",
    relatedId: [222],
    reading: "ベニチゴ",
    link: ""
  },
  {
    id: 222,
    name: "ラディカンス",
    scientificName: "Crassula pubescens ssp.radicans",
    fileName: "crassula-pubescens-ssp-radicans",
    family: "ベンケイソウ科",
    genus: "クラッスラ属",
    notes: "",
    relatedId: [221],
    reading: "ラディカンス",
    link: ""
  },
  {
    id: 223,
    name: "黄金花月",
    scientificName: "Crassula ovata 'Ougon'",
    fileName: "crassula-ovata-ougon",
    family: "ベンケイソウ科",
    genus: "クラッスラ属",
    notes: "",
    relatedId: [],
    reading: "オウゴンカゲツ",
    link: ""
  },
  {
    id: 224,
    name: "レモネード",
    scientificName: "Aeonium 'Lemonade'",
    fileName: "aeonium-lemonade",
    family: "ベンケイソウ科",
    genus: "アエオニウム属",
    notes: "",
    relatedId: [],
    reading: "レモネード",
    link: ""
  },
  {
    id: 225,
    name: "桜吹雪",
    scientificName: "Anacampseros rufescens 'Sakurafubuki'",
    fileName: "anacampseros-rufescens-sakurafubuki",
    family: "スベリヒユ科",
    genus: "アナカンプセロス属",
    notes: "",
    relatedId: [226, 227, 228],
    reading: "サクラフブキ",
    link: "/sakura-fubuki-garden-tips/"
  },
  {
    id: 226,
    name: "吹雪の松",
    scientificName: "Anacampseros rufescens 'Sakurafubuki'",
    fileName: "anacampseros-rufescens-sakurafubuki",
    family: "スベリヒユ科",
    genus: "アナカンプセロス属",
    notes: "",
    relatedId: [225, 227, 228],
    reading: "フブキノマツ",
    link: "/sakura-fubuki-garden-tips/"
  },
  {
    id: 227,
    name: "吹雪の松錦",
    scientificName: "Anacampseros rufescens 'Sakurafubuki'",
    fileName: "anacampseros-rufescens-sakurafubuki",
    family: "スベリヒユ科",
    genus: "アナカンプセロス属",
    notes: "",
    relatedId: [225, 226, 228],
    reading: "フブキノマツニシキ",
    link: "/sakura-fubuki-garden-tips/"
  },
  {
    id: 228,
    name: "姫吹雪",
    scientificName: "Anacampseros rufescens 'Sakurafubuki'",
    fileName: "anacampseros-rufescens-sakurafubuki",
    family: "スベリヒユ科",
    genus: "アナカンプセロス属",
    notes: "",
    relatedId: [225, 226, 227],
    reading: "ヒメフブキ",
    link: "/sakura-fubuki-garden-tips/"
  },
  {
    id: 229,
    name: "白牡丹",
    scientificName: "Graptoveria 'Titubans'",
    fileName: "graptoveria-titubans",
    family: "ベンケイソウ科",
    genus: "グラプトベリア属",
    notes: "",
    relatedId: [230],
    reading: "ハクボタン",
    link: "/echeveria-battle-whitepeony-vs-lightice/"
  },
  {
    id: 230,
    name: "ティテュバンス",
    scientificName: "Graptoveria 'Titubans'",
    fileName: "graptoveria-titubans",
    family: "ベンケイソウ科",
    genus: "グラプトベリア属",
    notes: "",
    relatedId: [229],
    reading: "ティテュバンス",
    link: "/echeveria-battle-whitepeony-vs-lightice/"
  },
  {
    id: 231,
    name: "プロリフィラ",
    scientificName: "Echeveria prolifica",
    fileName: "echeveria-prolifica",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [21],
    reading: "プロリフィラ",
    link: ""
  },
  {
    id: 232,
    name: "アロマティカス",
    scientificName: "Plectranthus amboinicus",
    fileName: "plectranthus-amboinicus",
    family: "シソ科",
    genus: "プレクトランサス属",
    notes: "",
    relatedId: [233, 234, 235],
    reading: "アロマティカス",
    link: ""
  },
  {
    id: 233,
    name: "キューバンオレガノ",
    scientificName: "Plectranthus amboinicus",
    fileName: "plectranthus-amboinicus",
    family: "シソ科",
    genus: "プレクトランサス属",
    notes: "",
    relatedId: [232, 234, 235],
    reading: "キューバンオレガノ",
    link: ""
  },
  {
    id: 234,
    name: "アンボイニクス",
    scientificName: "Plectranthus amboinicus",
    fileName: "plectranthus-amboinicus",
    family: "シソ科",
    genus: "プレクトランサス属",
    notes: "",
    relatedId: [232, 233, 235],
    reading: "アンボイニクス",
    link: ""
  },
  {
    id: 235,
    name: "アロマチクス",
    scientificName: "Plectranthus amboinicus",
    fileName: "plectranthus-amboinicus",
    family: "シソ科",
    genus: "プレクトランサス属",
    notes: "",
    relatedId: [232, 233, 234],
    reading: "アロマチクス",
    link: ""
  },
  {
    id: 236,
    name: "子宝草",
    scientificName: "Kalanchoe 'Creantodaigremontianum'",
    fileName: "kalanchoe-creantodaigremontianum",
    family: "ベンケイソウ科",
    genus: "カランコエ属",
    notes: "",
    relatedId: [237],
    reading: "コタカラソウ",
    link: "/kalanchoe-daigremontiana-care-guide/"
  },
  {
    id: 237,
    name: "クロンコエ",
    scientificName: "Kalanchoe 'Creantodaigremontianum'",
    fileName: "kalanchoe-creantodaigremontianum",
    family: "ベンケイソウ科",
    genus: "カランコエ属",
    notes: "",
    relatedId: [236],
    reading: "クロンコエ",
    link: "/kalanchoe-daigremontiana-care-guide/"
  },
  {
    id: 238,
    name: "ペンデンス",
    scientificName: "Cotyledon pendens",
    fileName: "cotyledon-pendens",
    family: "ベンケイソウ科",
    genus: "コチレドン属",
    notes: "",
    relatedId: [],
    reading: "ペンデンス",
    link: ""
  },
  {
    id: 240,
    name: "パールフォンニュルンベルグ",
    scientificName: "Echeveria 'Perle Von Nurnberg'",
    fileName: "",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [241, 242],
    reading: "パールフォンニュルンベルグ",
    link: ""
  },
  {
    id: 241,
    name: "パール フォン ニュルンベルグ",
    scientificName: "Echeveria 'Perle Von Nurnberg'",
    fileName: "",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [240, 242],
    reading: "パール フォン ニュルンベルグ",
    link: ""
  },
  {
    id: 242,
    name: "ニュルンベルグの真珠",
    scientificName: "Echeveria 'Perle Von Nurnberg'",
    fileName: "",
    family: "ベンケイソウ科",
    genus: "エケベリア属",
    notes: "",
    relatedId: [240, 241],
    reading: "ニュルンベルグノシンジュ",
    link: ""
  },
  {
    id: 243,
    name: "蒼星",
    scientificName: "Graptopetalum 'Sousei'",
    fileName: "graptopetalum-sousei",
    family: "ベンケイソウ科",
    genus: "グラプトペタルム属",
    notes: "",
    relatedId: [],
    reading: "ソウセイ",
    link: ""
  },
  {
    id: 244,
    name: "アドルフィ カッパー",
    scientificName: "Sedum adolphi 'Copper'",
    fileName: "sedum-adolphi-copper",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [245],
    reading: "アドルフィ カッパー",
    link: ""
  },
  {
    id: 245,
    name: "アドルフィ コッパー",
    scientificName: "Sedum adolphi 'Copper'",
    fileName: "sedum-adolphi-copper",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [244],
    reading: "アドルフィ コッパー",
    link: ""
  },
  {
    id: 246,
    name: "銘月",
    scientificName: "Sedum adolphi",
    fileName: "sedum-adolphi",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [247, 248, 249, 250],
    reading: "メイゲツ",
    link: "/sedum-adolphi-plant-profile/"
  },
  {
    id: 247,
    name: "アドルフィー",
    scientificName: "Sedum adolphi",
    fileName: "sedum-adolphi",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [246, 248, 249, 250],
    reading: "アドルフィー",
    link: "/sedum-adolphi-plant-profile/"
  },
  {
    id: 248,
    name: "メイゲツ",
    scientificName: "Sedum adolphi",
    fileName: "sedum-adolphi",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [246, 247, 249, 250],
    reading: "メイゲツ",
    link: "/sedum-adolphi-plant-profile/"
  },
  {
    id: 249,
    name: "名月",
    scientificName: "Sedum adolphi",
    fileName: "sedum-adolphi",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [246, 247, 248, 250],
    reading: "メイゲツ",
    link: "/sedum-adolphi-plant-profile/"
  },
  {
    id: 250,
    name: "明月",
    scientificName: "Sedum adolphi",
    fileName: "sedum-adolphi",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [246, 247, 248, 249],
    reading: "メイゲツ",
    link: "/sedum-adolphi-plant-profile/"
  },
  {
    id: 251,
    name: "メノマンネングサ",
    scientificName: "Sedum japonicum",
    fileName: "sedum-japonicum",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [252, 253, 254],
    reading: "メノマンネングサ",
    link: "/sedum-lineare-male-perennial/"
  },
  {
    id: 252,
    name: "女の万年草",
    scientificName: "Sedum japonicum",
    fileName: "sedum-japonicum",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [251, 253, 254],
    reading: "オンナノマンネングサ",
    link: "/sedum-lineare-male-perennial/"
  },
  {
    id: 253,
    name: "雌万年草",
    scientificName: "Sedum japonicum",
    fileName: "sedum-japonicum",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [251, 252, 254],
    reading: "メマンネングサ",
    link: "/sedum-lineare-male-perennial/"
  },
  {
    id: 254,
    name: "磯千鳥",
    scientificName: "Sedum japonicum",
    fileName: "sedum-japonicum",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [251, 252, 253],
    reading: "イソチドリ",
    link: "/sedum-lineare-male-perennial/"
  },
  {
    id: 255,
    name: "キャンプファイア",
    scientificName: "Crassula capitella 'Camp Fire'",
    fileName: "crassula-capitella-camp-fire",
    family: "ベンケイソウ科",
    genus: "クラッスラ属",
    notes: "",
    relatedId: [8],
    reading: "キャンプファイア",
    link: ""
  },
  {
    id: 256,
    name: "クーペリー",
    scientificName: "Sedum cooperi",
    fileName: "sedum-cooperi",
    family: "ベンケイソウ科",
    genus: "セダム属",
    notes: "",
    relatedId: [],
    reading: "クーペリー",
    link: ""
  },
  {
    id: 257,
    name: "ブロンズ姫",
    scientificName: "Graptopetalum paraguayensis 'Bronz'",
    fileName: "graptopetalum-paraguayensis-bronz",
    family: "ベンケイソウ科",
    genus: "グラプトペタルム属",
    notes: "",
    relatedId: [258, 259],
    reading: "ブロンズヒメ",
    link: ""
  },
  {
    id: 258,
    name: "ピーチ姫",
    scientificName: "Graptopetalum paraguayensis 'Bronz'",
    fileName: "graptopetalum-paraguayensis-bronz",
    family: "ベンケイソウ科",
    genus: "グラプトペタルム属",
    notes: "",
    relatedId: [257, 259],
    reading: "ピーチヒメ",
    link: ""
  },
  {
    id: 259,
    name: "姫朧月",
    scientificName: "Graptopetalum paraguayensis 'Bronz'",
    fileName: "graptopetalum-paraguayensis-bronz",
    family: "ベンケイソウ科",
    genus: "グラプトペタルム属",
    notes: "",
    relatedId: [257, 258],
    reading: "ヒメオボロヅキ",
    link: ""
  },
  {
    id: 260,
    name: "ルビーネックレス",
    scientificName: "Othonna capensis 'Ruby Necklace'",
    fileName: "othonna-capensis-ruby-necklace",
    family: "キク科",
    genus: "オトンナ属",
    notes: "",
    relatedId: [261, 262, 263, 264],
    reading: "ルビーネックレス",
    link: ""
  },
  {
    id: 261,
    name: "カペンシス",
    scientificName: "Othonna capensis 'Ruby Necklace'",
    fileName: "othonna-capensis-ruby-necklace",
    family: "キク科",
    genus: "オトンナ属",
    notes: "",
    relatedId: [260, 262, 263, 264],
    reading: "カペンシス",
    link: ""
  },
  {
    id: 262,
    name: "紫月",
    scientificName: "Othonna capensis 'Ruby Necklace'",
    fileName: "othonna-capensis-ruby-necklace",
    family: "キク科",
    genus: "オトンナ属",
    notes: "",
    relatedId: [260, 261, 263, 264],
    reading: "シズキ",
    link: ""
  },
  {
    id: 263,
    name: "パープルネックレス",
    scientificName: "Othonna capensis 'Ruby Necklace'",
    fileName: "othonna-capensis-ruby-necklace",
    family: "キク科",
    genus: "オトンナ属",
    notes: "",
    relatedId: [260, 261, 262, 264],
    reading: "パープルネックレス",
    link: ""
  },
  {
    id: 264,
    name: "黄花新月",
    scientificName: "Othonna capensis 'Ruby Necklace'",
    fileName: "othonna-capensis-ruby-necklace",
    family: "キク科",
    genus: "オトンナ属",
    notes: "",
    relatedId: [260, 261, 262, 263],
    reading: "キバナシンゲツ",
    link: ""
  },
  {
    id: 265,
    name: "ピーチネックレス",
    scientificName: "Senecio 'Peach Necklace'",
    fileName: "senecio-peach-necklace",
    family: "キク科",
    genus: "セネシオ属",
    notes: "",
    relatedId: [],
    reading: "ピーチネックレス",
    link: "/greenneck-peachneck/"
  },
  {
    id: 266,
    name: "赫麗",
    scientificName: "Crassula corymbosa",
    fileName: "crassula-corymbosa",
    family: "ベンケイソウ科",
    genus: "クラッスラ属",
    notes: "",
    relatedId: [267, 268],
    reading: "カクレイ",
    link: ""
  },
  {
    id: 267,
    name: "カクレイ",
    scientificName: "Crassula corymbosa",
    fileName: "crassula-corymbosa",
    family: "ベンケイソウ科",
    genus: "クラッスラ属",
    notes: "",
    relatedId: [266, 268],
    reading: "カクレイ",
    link: ""
  },
  {
    id: 268,
    name: "喜楽天",
    scientificName: "Crassula corymbosa",
    fileName: "crassula-corymbosa",
    family: "ベンケイソウ科",
    genus: "クラッスラ属",
    notes: "",
    relatedId: [266, 267],
    reading: "キラクテン",
    link: ""
  },
  {
    id: 269,
    name: "胡蝶の舞",
    scientificName: "Kalanchoe laxiflora",
    fileName: "kalanchoe-laxiflora",
    family: "ベンケイソウ科",
    genus: "カランコエ属",
    notes: "",
    relatedId: [270, 271],
    reading: "コチョウノマイ",
    link: ""
  },
  {
    id: 270,
    name: "鋸歯子持葉",
    scientificName: "Kalanchoe laxiflora",
    fileName: "kalanchoe-laxiflora",
    family: "ベンケイソウ科",
    genus: "カランコエ属",
    notes: "",
    relatedId: [269, 271],
    reading: "キョウシコモチバ",
    link: ""
  },
  {
    id: 271,
    name: "ラクシフローラ",
    scientificName: "Kalanchoe laxiflora",
    fileName: "kalanchoe-laxiflora",
    family: "ベンケイソウ科",
    genus: "カランコエ属",
    notes: "",
    relatedId: [269, 270],
    reading: "ラクシフローラ",
    link: ""
  },
  {
    id: 272,
    name: "デザートローズ",
    scientificName: "Kalanchoe luciae",
    fileName: "kalanchoe-luciae",
    family: "ベンケイソウ科",
    genus: "カランコエ属",
    notes: "",
    relatedId: [273, 274],
    reading: "デザートローズ",
    link: ""
  },
  {
    id: 273,
    name: "紅唐印",
    scientificName: "Kalanchoe luciae",
    fileName: "kalanchoe-luciae",
    family: "ベンケイソウ科",
    genus: "カランコエ属",
    notes: "",
    relatedId: [272, 274],
    reading: "ベニトウイン",
    link: ""
  },
  {
    id: 274,
    name: "ルキア",
    scientificName: "Kalanchoe luciae",
    fileName: "kalanchoe-luciae",
    family: "ベンケイソウ科",
    genus: "カランコエ属",
    notes: "",
    relatedId: [272, 273],
    reading: "ルキア",
    link: ""
  },
  {
    id: 275,
    name: "エンジェルティアーズ",
    scientificName: "Senecio herreanus f.variegata",
    fileName: "senecio-herreanus-variegata",
    family: "キク科",
    genus: "セネシオ属",
    notes: "",
    relatedId: [276, 277],
    reading: "エンジェルティアーズ",
    link: ""
  },
  {
    id: 276,
    name: "大弦月城錦",
    scientificName: "Senecio herreanus f.variegata",
    fileName: "senecio-herreanus-variegata",
    family: "キク科",
    genus: "セネシオ属",
    notes: "",
    relatedId: [275, 277],
    reading: "オオゲンゲツジョウニシキ",
    link: ""
  },
  {
    id: 277,
    name: "エンゼルティアーズ",
    scientificName: "Senecio herreanus f.variegata",
    fileName: "senecio-herreanus-variegata",
    family: "キク科",
    genus: "セネシオ属",
    notes: "",
    relatedId: [275, 276],
    reading: "エンゼルティアーズ",
    link: ""
  },
  {
    id: 278,
    name: "",
    scientificName: "",
    fileName: "",
    family: "",
    genus: "",
    notes: "",
    relatedId: [],
    reading: "",
    link: ""
  },
  {
    id: 279,
    name: "",
    scientificName: "",
    fileName: "",
    family: "",
    genus: "",
    notes: "",
    relatedId: [],
    reading: "",
    link: ""
  },
  {
    id: 280,
    name: "グリーンネックレス",
    scientificName: "Senecio rowleyanus",
    fileName: "senecio-rowleyanus",
    family: "キク科",
    genus: "セネシオ属",
    notes: "",
    relatedId: [281, 282, 283, 284],
    reading: "グリーンネックレス",
    link: "/greenneck-peachneck/"
  },
  {
    id: 281,
    name: "緑の鈴",
    scientificName: "Senecio rowleyanus",
    fileName: "senecio-rowleyanus",
    family: "キク科",
    genus: "セネシオ属",
    notes: "",
    relatedId: [280, 282, 283, 284],
    reading: "ミドリノスズ",
    link: "/greenneck-peachneck/"
  },
  {
    id: 282,
    name: "ミドリノスズ",
    scientificName: "Senecio rowleyanus",
    fileName: "senecio-rowleyanus",
    family: "キク科",
    genus: "セネシオ属",
    notes: "",
    relatedId: [280, 281, 283, 284],
    reading: "ミドリノスズ",
    link: "/greenneck-peachneck/"
  },
  {
    id: 283,
    name: "緑の玉",
    scientificName: "Senecio rowleyanus",
    fileName: "senecio-rowleyanus",
    family: "キク科",
    genus: "セネシオ属",
    notes: "",
    relatedId: [280, 281, 282, 284],
    reading: "ミドリノタマ",
    link: "/greenneck-peachneck/"
  },
  {
    id: 284,
    name: "翠玉簪",
    scientificName: "Senecio rowleyanus",
    fileName: "senecio-rowleyanus",
    family: "キク科",
    genus: "セネシオ属",
    notes: "",
    relatedId: [280, 281, 282, 283],
    reading: "スイギョクカンザシ",
    link: "/greenneck-peachneck/"
  },
  {
    id: 285,
    name: "サポナリア",
    scientificName: "Aloe saponaria",
    fileName: "aloe-saponaria",
    family: "キジカクシ科ツルボラン亜科",
    genus: "アロエ属",
    notes: "",
    relatedId: [286],
    reading: "サポナリア",
    link: ""
  },
  {
    id: 286,
    name: "明鱗錦",
    scientificName: "Aloe saponaria",
    fileName: "aloe-saponaria",
    family: "キジカクシ科ツルボラン亜科",
    genus: "アロエ属",
    notes: "",
    relatedId: [285],
    reading: "メイリンニシキ",
    link: ""
  },
  {
    id: 287,
    name: "",
    scientificName: "",
    fileName: "",
    family: "",
    genus: "",
    notes: "",
    relatedId: [],
    reading: "",
    link: ""
  },
  {
    id: 288,
    name: "",
    scientificName: "",
    fileName: "",
    family: "",
    genus: "",
    notes: "",
    relatedId: [],
    reading: "",
    link: ""
  },
  {
    id: 289,
    name: "ファング",
    scientificName: "Kalanchoe behalensis 'Fang'",
    fileName: "kalanchoe-behalensis-fang",
    family: "ベンケイソウ科",
    genus: "カランコエ属",
    notes: "",
    relatedId: [290, 291],
    reading: "ファング",
    link: ""
  },
  {
    id: 290,
    name: "ベハレンシス・ファング",
    scientificName: "Kalanchoe behalensis 'Fang'",
    fileName: "kalanchoe-behalensis-fang",
    family: "ベンケイソウ科",
    genus: "カランコエ属",
    notes: "",
    relatedId: [289, 291],
    reading: "ベハレンシス・ファング",
    link: ""
  },
  {
    id: 291,
    name: "ファーグ",
    scientificName: "Kalanchoe behalensis 'Fang'",
    fileName: "kalanchoe-behalensis-fang",
    family: "ベンケイソウ科",
    genus: "カランコエ属",
    notes: "",
    relatedId: [289, 290],
    reading: "ファーグ",
    link: ""
  },
  {
    id: 292,
    name: "月兎耳",
    scientificName: "Kalanchoe tomentosa",
    fileName: "kalanchoe-tomentosa",
    family: "ベンケイソウ科",
    genus: "カランコエ属",
    notes: "",
    relatedId: [],
    reading: "ツキトジ",
    link: ""
  },
  {
    id: 293,
    name: "不死鳥",
    scientificName: "Kalanchoe 'Fusityou'",
    fileName: "kalanchoe-fusityou",
    family: "ベンケイソウ科",
    genus: "カランコエ属",
    notes: "",
    relatedId: [],
    reading: "フシチョウ",
    link: "/phoenix-garden/"
  },
];

export default plants;
