import type { Metadata } from "next";
import Header from "@/app/components/Header";
import "./globals.css";
import "@/styles/fonts.css";
import "@/styles/clamps.css";

export const metadata: Metadata = {
  title: "Succulent planter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={""}>
        <Header />
        {children}
      </body>
    </html>
  );
}
